version: "3.8"

services:
  cloudimgs:
    # 使用 Docker Hub 上的镜像
    image: qazzxxx/cloudimgs:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - STORAGE_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    container_name: cloudimgs-app
