name: GitHub Packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        default: "latest"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Generate lowercase image name
        id: image_name
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "owner=$OWNER" >> $GITHUB_OUTPUT
          echo "image_name=ghcr.io/$OWNER/cloudimgs" >> $GITHUB_OUTPUT
          echo "Generated image name: ghcr.io/$OWNER/cloudimgs"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image_name.outputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=CloudImgs
            org.opencontainers.image.description=A modern image hosting application with React frontend and Node.js backend
            org.opencontainers.image.vendor=CloudImgs
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: |
            NODE_OPTIONS=--max-old-space-size=4096
          provenance: false

      - name: Success notification
        run: |
          echo "✅ GitHub Packages image published successfully!"
          echo "Image: ${{ steps.image_name.outputs.image_name }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Package URL: https://github.com/${{ github.repository }}/pkgs/container/cloudimgs"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ GitHub Packages publish failed!"
          echo "Please check the logs above for details."
          echo ""
          echo "Debug information:"
          echo "- Build context: ${{ github.workspace }}"
          echo "- Repository: ${{ github.repository }}"
          echo "- Repository Owner: ${{ github.repository_owner }}"
          echo "- Generated Image Name: ${{ steps.image_name.outputs.image_name }}"
          echo "- SHA: ${{ github.sha }}"
          echo "- Event: ${{ github.event_name }}"
          echo ""
          echo "Common solutions:"
          echo "1. Check if PAT_TOKEN secret is properly configured"
          echo "2. Verify repository permissions for packages"
          echo "3. Try building locally first with: ./test-build.sh"
          echo "4. Check for any syntax errors in the codebase"
