name: GitHub Packages (Simple)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.gha
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cloudimgs:latest
          platforms: linux/amd64
          build-args: |
            NODE_OPTIONS=--max-old-space-size=4096

      - name: Success notification
        run: |
          echo "✅ GitHub Packages image published successfully!"
          echo "Image: ghcr.io/${{ github.repository_owner }}/cloudimgs:latest"
